debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.example.board: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: ykmxxi
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 8.0 이상부터 사용
  jpa:
    defer-datasource-initialization: true # 테스트용 데이터베이스 데이터를 만들 수 있게 설정
    hibernate:
      ddl-auto: create # 엔티티를 보고 자동으로 DDL 생성
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
---
spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
